#!/bin/bash

#STORAGE ACCOUNT KEY
#YOU MUST EDIT THIS FOR THE SCRIPT TO ADD TO YOUR OWN QUEUE
#THE KEY IS PRESENTED AS AN OUTPUT FROM THE DEPLOYMENT TO AZURE
STORAGE_ACC_KEY=3yfqOC8KEmbgI/KDuq0AtUTuSi/Q8QjxgV6KSSg67szzIrGzApNxp3IzRTglv9dlpFXbF2mvh8+JlhPeC7Dm0Q==

#PARAMETERS BELOW THIS LINE CAN STAY UNCHANGED
STORAGE_ACC_NAME=twtqueue
QUEUE_NAME=twt
SCALE_SET_NAME=twtscaleset
RESOURCE_GROUP=twt
