#!/bin/bash

#STORAGE ACCOUNT KEY
#YOU MUST EDIT THIS FOR THE SCRIPT TO ADD TO YOUR OWN QUEUE
#THE KEY IS PRESENTED AS AN OUTPUT FROM THE DEPLOYMENT TO AZURE
STORAGE_ACC_KEY=<INSERT_STORAGE_KEY_HERE>
STORAGE_ACC_NAME=<INSERT_STORAGE_ACC_NAME_HERE>
RESOURCE_GROUP=<INSERT_RG_NAME_HERE>
#PARAMETERS BELOW THIS LINE CAN STAY UNCHANGED
QUEUE_NAME=twtqueue
SCALE_SET_NAME=twtscaleset

