trigger:

  branches:
    include:
    - master

stages:

- stage: test

  jobs:
  - job: test

    pool:
      name: Hosted Ubuntu 1604

    steps:

    - task: CmdLine@2
      inputs:
        script: 'echo Hello world'

- stage: deploy

  jobs:
  - job: deploy

    pool:
      name: Hosted Ubuntu 1604

    steps:

    - task: CmdLine@2
      inputs:
        script: 'echo Hello world'
